version: 1

services:
  flask:
    container_name: flask
    image: my-flask-image
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=my_flask_app.py
      - MONGO_URL=mongodb://mongodb:27017/mydb
    links:
      - mongodb
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - flask
  mongodb:
    container_name: mongodb
    image: mongo:latest
    volumes:
      - "./data:/data/db"
  vuejs:
    container_name: vuejs
    image: my-vuejs-image
    ports:
      - "8080:8080"
    volumes:
      - "./dist:/usr/share/nginx/html"
    depends_on:
      - nginx
